# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty
language: cpp

notifications:
  slack:
    rooms:
      - 7552-tallerii-2016-1c:IWVOUrDzz9erRJRZFF2GbzNs#grupo9

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential autotools-dev libboost-all-dev libicu-dev libsnappy-dev libbz2-dev zlib1g-dev gcovr lcov libcurl4-gnutls-dev libcrypto++-dev
  - wget -O boost_1_58_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz/download
  - tar xzf boost_1_58_0.tar.gz
  - cd boost_1_58_0/
  - ./bootstrap.sh --prefix=/usr/local
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -B. ../project && make
  - ./test/applib/testapp
